services:
  search:
    image: getmeili/meilisearch:v1.4
    ports:
      - 7700:7700
    volumes:
      - ./data/meili_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=_8ru_e8rwXWpeVZgAr-P8V_8wCFzQYb99AHWB52jzFY
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - MEILI_HTTP_ADDR=0.0.0.0:7700
      - MEILI_SERVER_PROVIDER=docker
      - MEILI_ENV=production
      - MEILI_NO_ANALYTICS=true
  backend:
    image: meili-backend:v1
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - MEILI_URL="${MEILI_URL}"
      - MEILI_MASTER_KEY="${MEILI_MASTER_KEY}"
    depends_on:
      - search
  frontend:
    image: meili-frontend:v1
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - BACKEND_URL="${BACKEND_URL}"
    depends_on:
      - backend
